### ISSUE TITLE
Could not locate SV_BroadcastVoice symbol!

### ISSUE THREAD

**Issue by JenyaRostov** [Meachamp/gm_8bit#1]
After doing `lua_run require("eightbit")` I get this error: Could not locate SV_BroadcastVoice symbol!
I'm running GMod 200818 on windows, x86. LuaJIT 2.0.4
![image](https://user-images.githubusercontent.com/52300935/91655125-2b06c480-eab7-11ea-8621-bfb3ed25dd70.png)

**Comment by Meachamp** [comment]
I am testing a fix right now. Thank you for your patience!

**Comment by Meachamp** [comment]
The latest build has measures in place that should address the issue. Please let me know if this fixed the problem for you.

**Comment by JenyaRostov** [comment]
Works fine, thanks!
