### ISSUE TITLE
Cant build windows binaries

### ISSUE THREAD

**Issue by Be1zebub** [Meachamp/gm_8bit#10]
![image](https://user-images.githubusercontent.com/34854689/202597132-9b06d836-0b29-41df-a74c-6857f9344287.png)
```
Run cd projects/windows/vs2019
&: D:\a\_temp\e7f6bf84-2547-46b0-82ce-673c5435e110.ps1:3
Line |
   3 |  & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSB …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\msbuild.exe' is not
     | recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name,
     | or if a path was included, verify that the path is correct and try again.
```
your builds are expired so no way to download it
![image](https://user-images.githubusercontent.com/34854689/202597306-7921b7e8-b916-40e5-ba11-540624273f55.png)

**Comment by Meachamp** [comment]
Thanks for the heads up! I've fixed the CI script and builds should be available now. I've also published the latest builds on the Releases page, so they should be available in the future even if the builds expired again.
