### ISSUE TITLE
Could not locate SV_BroadcastVoice symbol!

### ISSUE THREAD

**Issue by nifent** [Meachamp/gm_8bit#11]
Same error as #1 and #9 
Protocol version 24
Exe version 2022.06.08 (garrysmod)
Exe build: 17:35:41 Feb 20 2023 (8871) (4000)
GMod version 2023.04.19, branch: unknown, multicore: 0
Windows 32bit

"Could not locate SV_BroadcastVoice symbol!" error thrown when calling require("eightbit") in lua script.

**Comment by Meachamp** [comment]
It's likely signature related due to changes in that function. Will take a look at this when I can but time's a bit limited at the moment.

**Comment by nifent** [comment]
I was able to get around to digging into it and updated the function signature. I haven't tested e2e because I was using the function hook for another purpose, but it does locate and detour the function correctly.

https://github.com/Meachamp/gm_8bit/pull/12

**Comment by Meachamp** [comment]
I appreciate you looking into this. I just merged your PR - much appreciated.
