### ISSUE TITLE
Build artifacts are expired

### ISSUE THREAD

**Issue by osiris-plus** [Meachamp/gm_8bit#2]
The most recent commit has its build artifacts expired https://github.com/Meachamp/gm_8bit/actions/runs/232040489

**Comment by Meachamp** [comment]
Wasn't aware that build artifacts could expire, sorry about that. There should be a new build running right now, and afterwards I'll get a proper release up.

**Comment by osiris-plus** [comment]
Thanks. Already compiled myself though.

**Comment by osiris-plus** [comment]
Also voice-relay repository is nonexistent.
