### ISSUE TITLE
Feature Request: Configurable IP Address

### ISSUE THREAD

**Issue by oninoni** [Meachamp/gm_8bit#4]
Could you add a way, to set the IP and Port, that is used to send the packages to?
Our Server environment is virtualized and 127.0.0.1 only reaches the virtual GMod machine and not any external software.

**Comment by Meachamp** [comment]
Thanks for the request - this is something that needs to happen, and I'll see about doing it soon.

**Comment by Meachamp** [comment]
Should be good to go. Sorry for the wait.
