### ISSUE TITLE
Opus decompression fails assertion after steamclient.dll update

### ISSUE THREAD

**Issue by feversec** [Meachamp/gm_8bit#5]
I'm on Windows injecting my custom implementation (based on this RE) on the latest Gmod x86 update.
steamclient.dll has been updated and the original Opus codec factory signature seeks the wrong routine.
This is the new rebased CreateOpusPLCCodec offset: **0xC1540** (looks correct to me?)

Opus decompression is now breaking at a bool assertion site, no meaningful error info is provided.
> File: c:\buildslave\steam_rel_client_win32\build\src\p2pengine\p2pvoice\voiceencoder_opus.cpp
> Line: 408
> Assertion: Assertion Failed: false

**Comment by Meachamp** [comment]
Can you give me a SHA256 of the steamclient library you're using? Assertion 408 is a frame decode faillure. You've likely got the wrong constructor.

**Comment by feversec** [comment]
1C98D4D4F00ABE29F392AB36190C8B6F03152663F0EB3B937D2F8C1DE8B398A2
W10 x86 steamclient.dll
modified 3/23/2021 at 22:22

Looking for the other factory in IDA

**Comment by feversec** [comment]
Fixed, just like you said it's the wrong constructor. 
The one at **0xC14F0** works perfectly.
Thank you.

**Comment by Meachamp** [comment]
I hadn't really expected any of this code to be used on clients, unfortunately. I'll have to see if I can come up with a better way of locating the constructor, or I may re-implement valve's wrapper around opus.

**Comment by feversec** [comment]
I'm still hooking SV_BroadcastVoiceData with a bare minimum 500 line Source SDK 2013 header I made (I don't want it to rely on garrysmod_common), trying to make it cross-compatible with TF2 and other source games. I'm working on a standardized Gmod addon with basic SFX like butterworth LPF/HPF and STFT pitch scaling.

**Comment by Meachamp** [comment]
Would you be willing to share the incorrect signature you were using? I updated signatures a little while ago to make them more reliable, and the current windows x86 signature was actually able to handle this update properly. I'm curious what you were using, exactly. 

That's a very interesting project. I had wanted to write a better pitch scaling implementation for this module, but I'm not all that knowledgeable in DSP. If you would be interested in contributing any of that to the project, I would definitely be open to it.

**Comment by feversec** [comment]
It's the one in this repos, it is no longer pointing out to the OpusPLCCodec factory function but another unknown function.
Atleast that's what I deduced from searching it again using IDA and discovering it no longer works.

I have undergraduate physics knowledge tbh, I'm just relying on well-enstabilished real time DSP algorithms.
You can contact me on Discord if you want feversec#5038.
