### ISSUE TITLE
Cannot run DLL

### ISSUE THREAD

**Issue by oninoni** [Meachamp/gm_8bit#6]
I cannot run the dll on linux 32bit 

Log:

15.05. - 21:16:20 [gm_8bit] addons/gm_8bit/lua/autorun/server/gm_8bit_testing.lua:1: Couldn't load module library!
15.05. - 21:16:20   1. require - [C]:-1
15.05. - 21:16:20    2. unknown - addons/gm_8bit/lua/autorun/server/gm_8bit_testing.lua:1

File:

require("eightbit")
eightbit.EnableBroadcast(true)

**Comment by oninoni** [comment]
Using the linux 32 build from https://github.com/Meachamp/gm_8bit/actions/runs/766072570 btw

**Comment by Meachamp** [comment]
I'll take a look at it as soon as I can. Thanks for letting me know.

**Comment by Meachamp** [comment]
Can't reproduce this issue on an ubuntu 18.04 test machine. It might be your OS or environment. You might be able to use https://github.com/danielga/gmod_require to get the actual reason for why it isn't loading in your environment. I would suggest running `ldd` on the binary and making sure all the libs can be found (libtier0 not being found is fine).

**Comment by oninoni** [comment]
ips-hosting@Ubuntu-1810-cosmic-64-minimal:~/data/game-servers/543/garrysmod/lua/bin$ ldd gmsv_eightbit_linux.dll
        linux-gate.so.1 (0xf7f3c000)
        libtier0.so => not found
        libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf7d4b000)
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7c45000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7c27000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7a46000)
        /lib/ld-linux.so.2 (0xf7f3e000)

Will attempt gmod_require now

**Comment by oninoni** [comment]
17.05. - 09:56:02 [gm_8bit] error loading module 'eightbit' from file 'gmsv_eightbit_linux.dll':
17.05. - 09:56:02 	/home/ips-hosting/garrysmod/lua/bin/gmsv_eightbit_linux.dll: undefined symbol: g_pMemAlloc
17.05. - 09:56:02   1. error - [C]:-1
17.05. - 09:56:02    2. searcher - lua/includes/modules/require.lua:65
17.05. - 09:56:02     3. require - lua/includes/modules/require.lua:148
17.05. - 09:56:02      4. unknown - addons/gm_8bit/lua/autorun/server/gm_8bit_testing.lua:2
17.05. - 09:56:02

**Comment by oninoni** [comment]
its probably just not finding libtier0.so
Ill try EXPORT 'ing it and see if it works. will take a bit since im using an integrated hosting system i need to change the enviroment in.

**Comment by MilkGames** [comment]
Any updates on this?

**Comment by Meachamp** [comment]
Sorry about that, I thought this was resolved for some reason. I think it's still something related to the environment not being correct, but you can try building with NO_MALLOC_OVERRIDE preprocessor define to see if that helps. I don't have an environment where this issue occurs, so my hands are a little bit tied here.

**Comment by luttje** [comment]
Sorry to bump this, but this is what worked for me:

I checked my server /bin folder (e.g: `/home/steam/server_1/bin`) and noticed there wasn't a `libtier0.so` (only `libtier0_s.so` and `libtier0_srv.so`).

Symlinking to the `libtier0_s.so` worked for me:
```bash
ln -s libtier0_s.so libtier0.so
```

**Comment by brandonsturgeon** [comment]
@luttje Thanks, that worked for me too.

Interestingly, this is a new issue. This definitely wasn't happening a year or two ago when I was first messing with this module.
