### ISSUE TITLE
Could not load steamclient!

### ISSUE THREAD

**Issue by MilkGames** [Meachamp/gm_8bit#7]
[ERROR] Could not load steamclient!
  1. unknown - [C]:-1
   2. require - [C]:-1
    3. unknown - lua_run:1

On Linux 64 bit (grabbed from latest action)

**Comment by Meachamp** [comment]
I apologize for the wait, haven't had time to look into 64 bit issues until now. 

But - hopefully the wait was worth it! gm_8bit no longer requires access to the steamclient after great efforts in reverse engineering. The new implementation is available on experimental-opus for now, and should be merged after linux testing is done.

**Comment by MilkGames** [comment]
This is great to hear!
