### ISSUE TITLE
Could not locate SV_BroadcastVoice symbol!

### ISSUE THREAD

**Issue by DEXTER251** [Meachamp/gm_8bit#9]
Same error #1 
Protocol version 24
Exe version 2021.06.09 (garrysmod)
Exe build: 14:40:17 Jul 12 2021 (8283) (4000)
GMod version 2021.07.12, branch: unknown, multicore: 0
Windows 32bit
LuaJIT 2.0.4
![image](https://user-images.githubusercontent.com/64154463/145701114-5b5559a2-ca55-43c9-8869-c4b979ba4c7f.png)

**Comment by DEXTER251** [comment]
On linux CentOS 7 getting error "Couldn't load module library!"

**Comment by FlorianLeChat** [comment]
> On linux CentOS 7 getting error "Couldn't load module library!"

This is probably because a library used by this module is missing on your system or is too old. Try the command `ldd /path/to/<your_module_name>.dll` and see if an error appears.

**Comment by DEXTER251** [comment]
> > On linux CentOS 7 getting error "Couldn't load module library!"
> 
> This is probably because a library used by this module is missing on your system or is too old. Try the command `ldd /path/to/<your_module_name>.dll` and see if an error appears.

Unfortunately, the hosting from which I rent a server does not want to provide SSH access or update the system

**Comment by Meachamp** [comment]
It's likely the libc version that's being linked against, if the system is very old. There's not much that can be done, other than recompiling for your specific system.

**Comment by DEXTER251** [comment]
> It's likely the libc version that's being linked against, if the system is very old. There's not much that can be done, other than recompiling for your specific system.

it works. What about problem on windows?

**Comment by Meachamp** [comment]
The problem should be addressed in the latest build.

**Comment by DEXTER251** [comment]
> The problem should be addressed in the latest build.

Yep, it works. Thank you! <3
